version: '3.8'

services:
  portmonetka.authorization:
    build: ./
    command: ./wait-for-postgres.sh portmonetka.authorization.postgres ./portmonetka.authorization
    ports:
      - "8080:8080"
    depends_on:
      - portmonetka.authorization.postgres
    environment:
      POSTGRES_PASSWORD: "^+h9Cd~D/8JAHOB7"

  portmonetka.authorization.postgres:
    image: postgres:latest
    container_name: portmonetka.authorization.postgres
    environment:
      POSTGRES_PASSWORD: "^+h9Cd~D/8JAHOB7"
    ports:
      - "5432:5432"
    volumes:
      - ${HOME}/Projects/PortmonetkaData/postgres:/var/lib/postgresql/data